<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $skincare = Category::where('slug', 'skincare')->first();
        $maquillage = Category::where('slug', 'maquillage')->first();
        $accessoires = Category::where('slug', 'accessoires')->first();

        // ========== ACCESSOIRES ==========
        Product::create(['category_id' => $accessoires->id, 'name' => 'Mini Brush Set', 'description' => 'Set de pinceaux miniatures', 'price' => 15.99, 'brand' => 'Glowi', 'product_type' => 'Pinceau', 'image' => 'accessoires/10miniBrush.png', 'stock' => 20, 'active' => true]);
        Product::create(['category_id' => $accessoires->id, 'name' => 'Brosse à Cheveux', 'description' => 'Brosse démêlante en bois', 'price' => 12.50, 'brand' => 'Glowi', 'product_type' => 'Brosse', 'image' => 'accessoires/BrosseAcheveux.png', 'stock' => 15, 'active' => true]);
        Product::create(['category_id' => $accessoires->id, 'name' => 'Coton Démaquillant', 'description' => 'Cotons doux x50', 'price' => 4.99, 'brand' => 'Glowi', 'product_type' => 'Coton', 'image' => 'accessoires/coton.png', 'stock' => 50, 'active' => true]);
        Product::create(['category_id' => $accessoires->id, 'name' => 'Éponge Konjac', 'description' => 'Éponge naturelle visage', 'price' => 6.99, 'brand' => 'Glowi', 'product_type' => 'Éponge', 'image' => 'accessoires/eponge.png', 'stock' => 25, 'active' => true]);
        Product::create(['category_id' => $accessoires->id, 'name' => 'Essence Coure-Cil', 'description' => 'Pince à épiler professionnelle', 'price' => 8.99, 'brand' => 'Glowi', 'product_type' => 'Pince', 'image' => 'accessoires/EssenceCoureCil.png', 'stock' => 30, 'active' => true]);
        Product::create(['category_id' => $accessoires->id, 'name' => 'Ti Tana', 'description' => 'Pince multifonction', 'price' => 7.99, 'brand' => 'Glowi', 'product_type' => 'Pince', 'image' => 'accessoires/TiTana.png', 'stock' => 20, 'active' => true]);

        // ========== MAQUILLAGE - GLOSS ==========
        Product::create(['category_id' => $maquillage->id, 'name' => 'Comfort Lip Liner', 'description' => 'Lip liner confortable', 'price' => 9.99, 'brand' => 'Glowi', 'product_type' => 'Gloss', 'image' => 'maquillage/Gloss/_HmATTEcOMFORTlIPLINER.png', 'stock' => 35, 'active' => true]);

        // ========== MAQUILLAGE - TEINT ==========
        Product::create(['category_id' => $maquillage->id, 'name' => 'Baby Got Glow Highliter', 'description' => 'Highlighter illuminateur', 'price' => 19.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/babygOTgLOWHighliter.png', 'stock' => 20, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Banana Loose Powder', 'description' => 'Poudre libre banana', 'price' => 22.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/banaLOOsePowder.png', 'stock' => 18, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Banana Powder Brighten Up', 'description' => 'Poudre illuminatrice', 'price' => 24.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/BANANAPOUDERBRIGHTENUP.png', 'stock' => 15, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Blush Crush', 'description' => 'Blush naturel longue tenue', 'price' => 16.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/blushCrush.png', 'stock' => 25, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Boucy Blur Blush', 'description' => 'Blush effet flou', 'price' => 18.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/boucyBlurBlush.png', 'stock' => 20, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Bouncy Plump Primer', 'description' => 'Primer lissant repulpant', 'price' => 21.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/bouncyPlumpSmoothingPrimer.png', 'stock' => 18, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Camouflage Concealer', 'description' => 'Correcteur couvrance totale', 'price' => 14.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/camouflage+correcteurconcealer.png', 'stock' => 30, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Fix and Last', 'description' => 'Spray fixateur longue tenue', 'price' => 12.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/fixAndLast.png', 'stock' => 22, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Flawless Concealer', 'description' => 'Anticernes parfait', 'price' => 13.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/flawlessConcealer.png', 'stock' => 28, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Foundation Essence', 'description' => 'Fond de teint essence', 'price' => 26.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/foundationEssencce.png', 'stock' => 15, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Jelly Glow', 'description' => 'Fond de teint effet gelée', 'price' => 23.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/jellyGlow.png', 'stock' => 20, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Jelly Grip Aloe Spray', 'description' => 'Spray fixateur à l\'aloé vera', 'price' => 11.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/jellyGripRefreshingALOESPRAY.png', 'stock' => 25, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Liquid Highliter', 'description' => 'Highlighter liquide', 'price' => 17.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/liquidHighliter.png', 'stock' => 18, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Revolution Bronzer', 'description' => 'Bronzer effet bonne mine', 'price' => 15.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/revolutionBronzer.png', 'stock' => 22, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Revolution Powder Pops', 'description' => 'Poudre de finition', 'price' => 19.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/RevolutionPowderPopsINSTANTBlurSettingPowder.png', 'stock' => 16, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Revolution Skin Silk', 'description' => 'Fond de teint satiné', 'price' => 24.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/revolutionSkinSilkRadiant.png', 'stock' => 14, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Sensitive Concealer', 'description' => 'Correcteur peaux sensibles', 'price' => 13.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/sensitiveConcealer.png', 'stock' => 20, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Skin Tint', 'description' => 'Teinte de peau légère', 'price' => 20.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/skinTint.png', 'stock' => 18, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Super Fix Misting Spray', 'description' => 'Spray fixateur ultra tenue', 'price' => 14.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/superFixMistingSettingSpray.png', 'stock' => 24, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Under Eye Concealer', 'description' => 'Correcteur cernes illuminateur', 'price' => 15.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/underEyeBrightiningConcealer.png', 'stock' => 22, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'What A Tint Encre Joues', 'description' => 'Encre joues et lèvres', 'price' => 18.99, 'brand' => 'Glowi', 'product_type' => 'Teint', 'image' => 'maquillage/teint/whatATintEncreJouesEtLevre.png', 'stock' => 19, 'active' => true]);

        // ========== MAQUILLAGE - YEUX ==========
        Product::create(['category_id' => $maquillage->id, 'name' => 'Crazy Volume Mascara', 'description' => 'Mascara volume intense', 'price' => 14.99, 'brand' => 'Glowi', 'product_type' => 'Yeux', 'image' => 'maquillage/yeux/crazyVolumeMascara.png', 'stock' => 30, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Eyebrow Pommade', 'description' => 'Pommade sourcils', 'price' => 11.99, 'brand' => 'Glowi', 'product_type' => 'Yeux', 'image' => 'maquillage/yeux/eyebrowPommades.png', 'stock' => 25, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Eyeliner Waterproof', 'description' => 'Eyeliner résistant à l\'eau', 'price' => 10.99, 'brand' => 'Glowi', 'product_type' => 'Yeux', 'image' => 'maquillage/yeux/EyelinerWaterproof.png', 'stock' => 35, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Gel Sourcils Liftant', 'description' => 'Gel fixateur sourcils', 'price' => 9.99, 'brand' => 'Glowi', 'product_type' => 'Yeux', 'image' => 'maquillage/yeux/gelAsourcilsLiftant.png', 'stock' => 28, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Glitter Stick Paillettes', 'description' => 'Stick pailleté pour les yeux', 'price' => 12.99, 'brand' => 'Glowi', 'product_type' => 'Yeux', 'image' => 'maquillage/yeux/glitterStickPallerres.png', 'stock' => 20, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Inner Eye Khol', 'description' => 'Khôl yeux intérieur', 'price' => 8.99, 'brand' => 'Glowi', 'product_type' => 'Yeux', 'image' => 'maquillage/yeux/innerEyeKhol.png', 'stock' => 32, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Kajal Pencil', 'description' => 'Crayon kajal intense', 'price' => 9.99, 'brand' => 'Glowi', 'product_type' => 'Yeux', 'image' => 'maquillage/yeux/kajalPencilCrayonYeux.png', 'stock' => 30, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Liquid Eyeliner', 'description' => 'Eyeliner liquide précision', 'price' => 11.99, 'brand' => 'Glowi', 'product_type' => 'Yeux', 'image' => 'maquillage/yeux/LiquidEyeliner.png', 'stock' => 28, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Mascara Effet Faux Cils', 'description' => 'Mascara volumisant faux cils', 'price' => 16.99, 'brand' => 'Glowi', 'product_type' => 'Yeux', 'image' => 'maquillage/yeux/mascaraEffetFauxCils.png', 'stock' => 25, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Mascara Make Me Brow', 'description' => 'Mascara sourcils', 'price' => 13.99, 'brand' => 'Glowi', 'product_type' => 'Yeux', 'image' => 'maquillage/yeux/mascaraMakeMeBrow.png', 'stock' => 22, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Palette Brown', 'description' => 'Palette ombres brunes', 'price' => 29.99, 'brand' => 'Glowi', 'product_type' => 'Yeux', 'image' => 'maquillage/yeux/paletteBrown.png', 'stock' => 15, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Palette Nude', 'description' => 'Palette ombres nude', 'price' => 29.99, 'brand' => 'Glowi', 'product_type' => 'Yeux', 'image' => 'maquillage/yeux/paletteNude.png', 'stock' => 15, 'active' => true]);
        Product::create(['category_id' => $maquillage->id, 'name' => 'Waterproof Mascara', 'description' => 'Mascara waterproof longue tenue', 'price' => 15.99, 'brand' => 'Glowi', 'product_type' => 'Yeux', 'image' => 'maquillage/yeux/WaterproofMascara.png', 'stock' => 28, 'active' => true]);

        // ========== SKINCARE ==========
        Product::create(['category_id' => $skincare->id, 'name' => 'ACM Azéane', 'description' => 'Soin dépigmentant', 'price' => 34.99, 'brand' => 'ACM', 'product_type' => 'Sérum', 'image' => 'skincare/acmAzéane.png', 'stock' => 12, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'ACM Dépiwhite', 'description' => 'Crème dépigmentante', 'price' => 32.99, 'brand' => 'ACM', 'product_type' => 'Crème', 'image' => 'skincare/acmDépiwhite.png', 'stock' => 10, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Active Sebiaclear', 'description' => 'Soin anti-imperfections', 'price' => 22.99, 'brand' => 'Bioderma', 'product_type' => 'Soin', 'image' => 'skincare/activeSebiaclear.png', 'stock' => 15, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Atoclean Bioderma', 'description' => 'Nettoyant peaux atopiques', 'price' => 18.99, 'brand' => 'Bioderma', 'product_type' => 'Nettoyant', 'image' => 'skincare/atocleanBioderma.png', 'stock' => 20, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Atoderm Bioderma', 'description' => 'Crème corps nourrissante', 'price' => 24.99, 'brand' => 'Bioderma', 'product_type' => 'Crème', 'image' => 'skincare/atodermbioderma.png', 'stock' => 18, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Avène Hydrance', 'description' => 'Crème hydratante Avène', 'price' => 28.99, 'brand' => 'Avène', 'product_type' => 'Crème', 'image' => 'skincare/avaneHydrance.png', 'stock' => 14, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Avène Cleanance', 'description' => 'Soin peaux à tendance acnéique', 'price' => 21.99, 'brand' => 'Avène', 'product_type' => 'Soin', 'image' => 'skincare/aveneCleanance.png', 'stock' => 16, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Avène Hydrance+', 'description' => 'Hydratation intense', 'price' => 29.99, 'brand' => 'Avène', 'product_type' => 'Crème', 'image' => 'skincare/avéneHydrance.png', 'stock' => 12, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'B3 Sérum', 'description' => 'Sérum Niacinamide B3', 'price' => 19.99, 'brand' => 'Glowi', 'product_type' => 'Sérum', 'image' => 'skincare/B3.png', 'stock' => 20, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Bioderma Atoderm', 'description' => 'Soin peaux sèches', 'price' => 22.99, 'brand' => 'Bioderma', 'product_type' => 'Soin', 'image' => 'skincare/biodermaatoderma.png', 'stock' => 15, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Bioderma C-Correction', 'description' => 'Soin pigment correcteur', 'price' => 35.99, 'brand' => 'Bioderma', 'product_type' => 'Sérum', 'image' => 'skincare/BiodermaC-correctionPigmentBio.png', 'stock' => 10, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Bioderma Pigment', 'description' => 'Soin anti-taches', 'price' => 27.99, 'brand' => 'Bioderma', 'product_type' => 'Soin', 'image' => 'skincare/biodermapigment.png', 'stock' => 12, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Cicavit+', 'description' => 'Crème réparatrice cicatrisante', 'price' => 16.99, 'brand' => 'Glowi', 'product_type' => 'Crème', 'image' => 'skincare/cicavit+.png', 'stock' => 18, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Eau Micellaire', 'description' => 'Eau micellaire démaquillante', 'price' => 14.99, 'brand' => 'Glowi', 'product_type' => 'Nettoyant', 'image' => 'skincare/eauMicellaire.png', 'stock' => 25, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Eau Micellaire SVR', 'description' => 'Eau micellaire Physiopure', 'price' => 16.99, 'brand' => 'SVR', 'product_type' => 'Nettoyant', 'image' => 'skincare/eaumicellairePhysiopureSvr.png', 'stock' => 20, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Gel Nettoyant', 'description' => 'Gel nettoyant doux visage', 'price' => 13.99, 'brand' => 'Glowi', 'product_type' => 'Nettoyant', 'image' => 'skincare/gelNettoyant.png', 'stock' => 22, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Pack Concombre', 'description' => 'Masque concombre hydratant', 'price' => 11.99, 'brand' => 'Glowi', 'product_type' => 'Masque', 'image' => 'skincare/packConcombre.png', 'stock' => 28, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Physiopure SVR', 'description' => 'Soin purifiant SVR', 'price' => 18.99, 'brand' => 'SVR', 'product_type' => 'Soin', 'image' => 'skincare/physiopuresvr.png', 'stock' => 15, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Pigment Bio', 'description' => 'Soin anti-pigmentation', 'price' => 26.99, 'brand' => 'Glowi', 'product_type' => 'Sérum', 'image' => 'skincare/pigmentbio.png', 'stock' => 12, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Pigment Bio Bioderma', 'description' => 'Soin dépigmentant Bioderma', 'price' => 31.99, 'brand' => 'Bioderma', 'product_type' => 'Sérum', 'image' => 'skincare/pigmentbioBioderma.png', 'stock' => 10, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Sensibio Gel Nettoyant', 'description' => 'Gel nettoyant peaux sensibles', 'price' => 17.99, 'brand' => 'Bioderma', 'product_type' => 'Nettoyant', 'image' => 'skincare/sensibioGelNettoyant.png', 'stock' => 18, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Sensibio Micellaire', 'description' => 'Eau micellaire peaux sensibles', 'price' => 15.99, 'brand' => 'Bioderma', 'product_type' => 'Nettoyant', 'image' => 'skincare/sensibioMicellaireBioderma.png', 'stock' => 22, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Sérum Concombre', 'description' => 'Sérum hydratant concombre', 'price' => 19.99, 'brand' => 'Glowi', 'product_type' => 'Sérum', 'image' => 'skincare/serumConcobre.png', 'stock' => 16, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'SPF 50', 'description' => 'Protection solaire SPF 50', 'price' => 23.99, 'brand' => 'Glowi', 'product_type' => 'Solaire', 'image' => 'skincare/spf50.png', 'stock' => 20, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'SVR Déo', 'description' => 'Déodorant SVR', 'price' => 12.99, 'brand' => 'SVR', 'product_type' => 'Déodorant', 'image' => 'skincare/svrDeo.png', 'stock' => 24, 'active' => true]);
        Product::create(['category_id' => $skincare->id, 'name' => 'Zynia Lait Hydratant', 'description' => 'Lait corps hydratant', 'price' => 14.99, 'brand' => 'Glowi', 'product_type' => 'Hydratant', 'image' => 'skincare/zyniaLaitHydratant.png', 'stock' => 20, 'active' => true]);
    }
}